import { createPdf, addReportHeader, addAutoTable, savePdf } from '../../utils/pdfGenerator';
import { formatLocalTime } from '../../utils/companyLocalDisplay';
import { IST } from '../../utils/istDisplay';
import { formatWorkedHours } from '../../utils/durationFormat';

function makeTimeHelpers(timezone = IST) {
  const tz = timezone || IST;

  function getFirstInTime(row) {
    const firstIn = (row.punches || []).find(
      (p) => String(p.punch_type || '').toLowerCase() === 'in'
    );
    return firstIn?.punch_time ? formatLocalTime(firstIn.punch_time, tz) : '—';
  }

  function formatPunchTimings(punches) {
    const list = Array.isArray(punches) ? punches : [];
    if (list.length === 0) return '';
    return list
      .map((p) => {
        const timeLabel = p?.punch_time ? formatLocalTime(p.punch_time, tz) : '';
        const typeLabel = String(p?.punch_type || '').toLowerCase() === 'out' ? 'OUT' : 'IN';
        return timeLabel ? `${timeLabel} (${typeLabel})` : '';
      })
      .filter(Boolean)
      .join(', ');
  }

  return { getFirstInTime, formatPunchTimings };
}

function getDayStatusLabel(row) {
  if (!row.present) return 'Absent';
  if (row.full_day) return row.late ? 'Full day (late)' : 'Full day';
  if (row.half_day) return row.late ? 'Half day (late)' : 'Half day';
  if (row.left_during_lunch) return 'Left at lunch';
  return row.late ? 'Present (late)' : 'Present';
}

function getDayTotalHours(row) {
  if (row.total_hours_inside != null) return formatWorkedHours(row.total_hours_inside);
  if (row.total_hours_from_shift_start != null) return formatWorkedHours(row.total_hours_from_shift_start);
  return '';
}

function sectionTitle(doc, y, text, fontSize = 10) {
  doc.setFontSize(fontSize);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(text, 24, y);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);
  return y + 12;
}

function tableAfterTitle(doc, head, body, startY, options = {}) {
  addAutoTable(doc, head, body, {
    startY,
    margin: { left: 24, right: 24 },
    styles: { fontSize: 8, cellPadding: 3 },
    ...options,
  });
  return doc.lastAutoTable?.finalY != null ? doc.lastAutoTable.finalY + 18 : startY + 40;
}

export function buildDayWiseWhatsAppMessage({
  companyName,
  dateLabel,
  departmentLabel,
  branchLabel,
  summary,
  absentees,
}) {
  const absentRows = Array.isArray(absentees) ? absentees : [];

  const lines = ['*Day-wise Attendance Report*', `*Date:* ${dateLabel}`];
  if (branchLabel) lines.push(`*Branch:* ${branchLabel}`);
  if (departmentLabel) lines.push(`*Department:* ${departmentLabel}`);
  if (companyName) lines.push(`*Company:* ${companyName}`);
  lines.push('');
  lines.push('*Summary:*');
  lines.push(
    `*Total:* ${summary.total} | *Present:* ${summary.present} | *Absent:* ${summary.absent}`
  );
  lines.push(
    `*Late:* ${summary.late} | *Full day:* ${summary.fullDay} | *Overtime:* ${summary.overtimeHours} h`
  );
  lines.push('');
  lines.push(`*Absentees (${absentRows.length}):*`);
  if (absentRows.length === 0) {
    lines.push('- None');
  } else {
    absentRows.forEach((row, idx) => {
      lines.push(`${idx + 1}. ${row?.name || 'Unknown'}`);
    });
  }
  lines.push('');
  lines.push('Generated by PunchPay');
  return lines.join('\n');
}

/**
 * Build day-wise PDF document (summary, absentees, late comers, all employees).
 */
export function buildDayWiseReportDoc({
  company,
  dateLabel,
  departmentLabel,
  branchLabel,
  summary,
  absentees,
  lateComers,
  allEmployees,
  timezone,
}) {
  const { getFirstInTime, formatPunchTimings } = makeTimeHelpers(timezone || company?.timezone);
  const scopeParts = [dateLabel, branchLabel, departmentLabel].filter(Boolean);
  const doc = createPdf({ orientation: 'portrait' });
  let y = addReportHeader(doc, {
    companyName: company?.name,
    companyPhone: company?.phone,
    companyAddress: company?.address,
    title: 'Day-wise Attendance Report',
    periodLabel: scopeParts.join(' · '),
    generatedAt: new Date().toLocaleString(),
    totalEmployees: summary.total,
  });

  y = sectionTitle(doc, y, 'Summary', 12);
  y = tableAfterTitle(
    doc,
    [['Total', 'Present', 'Absent', 'Late', 'Full day', 'Overtime (h)']],
    [
      [
        summary.total,
        summary.present,
        summary.absent,
        summary.late,
        summary.fullDay,
        summary.overtimeHours,
      ],
    ],
    y,
    {
      headStyles: { fillColor: [30, 64, 175] },
      styles: { fontSize: 10, cellPadding: 2.5 },
    }
  );

  y = sectionTitle(doc, y, `Absentees (${absentees.length})`);
  y = tableAfterTitle(
    doc,
    [['Employee', 'Code', 'Branch']],
    absentees.length
      ? absentees.map((row) => [row.name || '—', row.employee_code || '—', row.branch_name || '—'])
      : [['—', '—', 'No absentees']],
    y
  );

  y = sectionTitle(doc, y, `Late comers (${lateComers.length})`);
  y = tableAfterTitle(
    doc,
    [['Employee', 'Code', 'Arrival', 'Minutes late']],
    lateComers.length
      ? lateComers.map((row) => [
          row.name || '—',
          row.employee_code || '—',
          getFirstInTime(row),
          row.minutes_late != null && row.minutes_late > 0
            ? `${Math.round(row.minutes_late)}`
            : '—',
        ])
      : [['—', '—', '—', 'No late arrivals']],
    y,
    { headStyles: { fillColor: [180, 83, 9] } }
  );

  if (y > doc.internal.pageSize.getHeight() - 120) {
    doc.addPage();
    y = 32;
  }

  y = sectionTitle(doc, y, `All employees (${allEmployees.length})`);
  tableAfterTitle(
    doc,
    [['Employee', 'Code', 'Branch', 'Status', 'Punch timings', 'Hours', 'OT (h)']],
    allEmployees.map((row) => [
      row.name || '—',
      row.employee_code || '—',
      row.branch_name || '—',
      getDayStatusLabel(row),
      formatPunchTimings(row.punches),
      getDayTotalHours(row) || '—',
      row.overtime_hours != null && row.overtime_hours > 0 ? String(row.overtime_hours) : '—',
    ]),
    y
  );

  return doc;
}

export function buildDayWiseReportPdfBlob(payload, filename = 'daily-attendance.pdf') {
  const doc = buildDayWiseReportDoc(payload);
  return {
    blob: doc.output('blob'),
    filename,
  };
}

/**
 * Download day-wise PDF.
 */
export async function generateDayWiseReportPdf({ filename, ...payload }) {
  const doc = buildDayWiseReportDoc(payload);
  savePdf(doc, filename || 'daily-attendance.pdf');
}

function escapeCsvCell(value) {
  const str = value == null ? '' : String(value);
  if (/[,"\r\n]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function csvRow(cells) {
  return cells.map(escapeCsvCell).join(',');
}

/**
 * Build multi-section CSV matching the on-screen day-wise report.
 */
export function buildDayWiseReportCsv({
  dateLabel,
  departmentLabel,
  branchLabel,
  summary,
  absentees,
  lateComers,
  allEmployees,
  timezone,
}) {
  const { getFirstInTime, formatPunchTimings } = makeTimeHelpers(timezone);
  const lines = [];
  lines.push(csvRow(['Day-wise Attendance Report']));
  lines.push(csvRow(['Date', dateLabel]));
  if (branchLabel) lines.push(csvRow(['Branch', branchLabel]));
  if (departmentLabel) lines.push(csvRow(['Department', departmentLabel]));
  lines.push('');

  lines.push(csvRow(['Summary']));
  lines.push(csvRow(['Total', 'Present', 'Absent', 'Late', 'Full day', 'Overtime (h)']));
  lines.push(
    csvRow([
      summary.total,
      summary.present,
      summary.absent,
      summary.late,
      summary.fullDay,
      summary.overtimeHours,
    ])
  );
  lines.push('');

  lines.push(csvRow([`Absentees (${absentees.length})`]));
  lines.push(csvRow(['Employee', 'Code', 'Branch']));
  if (absentees.length === 0) {
    lines.push(csvRow(['No absentees', '', '']));
  } else {
    absentees.forEach((row) => {
      lines.push(csvRow([row.name || '', row.employee_code || '', row.branch_name || '']));
    });
  }
  lines.push('');

  lines.push(csvRow([`Late comers (${lateComers.length})`]));
  lines.push(csvRow(['Employee', 'Code', 'Arrival', 'Minutes late']));
  if (lateComers.length === 0) {
    lines.push(csvRow(['No late arrivals', '', '', '']));
  } else {
    lateComers.forEach((row) => {
      lines.push(
        csvRow([
          row.name || '',
          row.employee_code || '',
          getFirstInTime(row),
          row.minutes_late != null && row.minutes_late > 0
            ? Math.round(row.minutes_late)
            : '',
        ])
      );
    });
  }
  lines.push('');

  lines.push(csvRow([`All employees (${allEmployees.length})`]));
  lines.push(
    csvRow(['Employee', 'Code', 'Branch', 'Status', 'Punch timings', 'Hours', 'OT (h)'])
  );
  allEmployees.forEach((row) => {
    lines.push(
      csvRow([
        row.name || '',
        row.employee_code || '',
        row.branch_name || '',
        getDayStatusLabel(row),
        formatPunchTimings(row.punches),
        getDayTotalHours(row),
        row.overtime_hours != null && row.overtime_hours > 0 ? row.overtime_hours : '',
      ])
    );
  });

  return `${lines.join('\r\n')}\r\n`;
}

export function downloadDayWiseReportCsv(csvContent, filename) {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' });
  const blobUrl = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = blobUrl;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(blobUrl);
}
