import { useMemo } from 'react';
import { createPdf, savePdf } from '../../utils/pdfGenerator';

function formatMoney(n) {
  if (n == null || Number.isNaN(Number(n))) return '—';
  return new Intl.NumberFormat('en-IN', {
    style: 'decimal',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(Number(n));
}

export default function PayslipModal({
  open,
  onClose,
  company,
  payrollRow,
  breakdown,
  attendanceDetails,
}) {
  const periodLabel = useMemo(() => {
    if (!payrollRow) return '';
    const d = new Date(payrollRow.year, payrollRow.month - 1, 1);
    return d.toLocaleString('default', { month: 'long', year: 'numeric' });
  }, [payrollRow]);

  if (!open || !payrollRow || !breakdown) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPdf = () => {
    const doc = createPdf();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 32;

    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text(String(company?.name || 'Company'), pageWidth / 2, y, { align: 'center' });
    y += 14;
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    const addressLine = [company?.address, company?.phone, company?.email].filter(Boolean).join(' | ');
    if (addressLine) {
      doc.text(addressLine, pageWidth / 2, y, { align: 'center' });
      y += 12;
    }
    doc.setLineWidth(0.5);
    doc.line(40, y, pageWidth - 40, y);

    y += 18;
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('PAYSLIP', pageWidth / 2, y, { align: 'center' });
    y += 12;
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.text(`Month: ${periodLabel}`, pageWidth / 2, y, { align: 'center' });

    y += 20;
    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.text('EMPLOYEE DETAILS', 40, y);
    y += 10;
    doc.setFont(undefined, 'normal');
    const leftX = 40;
    const midX = 220;
    const lines = [
      ['Employee Name', payrollRow.employee_name],
      ['Employee Code', payrollRow.employee_code],
      ['Designation', attendanceDetails?.designation || ''],
      ['Department', attendanceDetails?.department || ''],
      ['Date of Joining', attendanceDetails?.join_date || ''],
      ['Shift', attendanceDetails?.shift_name || ''],
    ];
    lines.forEach(([label, value], idx) => {
      const targetX = idx < 3 ? leftX : midX;
      const rowY = y + (Math.floor(idx / 2) * 12);
      doc.text(`${label} : ${value || '—'}`, targetX, rowY);
    });

    y += 40;
    doc.setFont(undefined, 'bold');
    doc.text('ATTENDANCE SUMMARY', 40, y);
    y += 10;
    doc.setFont(undefined, 'normal');
    const att = breakdown.attendance;
    const attLines = [
      ['Working Days', att?.workingDays ?? '—'],
      ['Days Present', att?.presentDays ?? '—'],
      ['Days Absent', att?.absenceDays ?? '—'],
      ['Half Days', attendanceDetails?.halfDayCount ?? '—'],
      ['Late Arrivals', attendanceDetails?.lateCount ?? '—'],
      ['Overtime Hours', att?.overtimeHours ?? '—'],
    ];
    attLines.forEach(([label, value], idx) => {
      const rowY = y + idx * 12;
      doc.text(`${label} : ${value}`, 40, rowY);
    });

    y += 80;
    doc.setFont(undefined, 'bold');
    doc.text('EARNINGS', 40, y);
    doc.text('DEDUCTIONS', pageWidth / 2 + 20, y);
    y += 10;
    doc.setFont(undefined, 'normal');

    const b = breakdown.breakdown;
    const earnings = [
      ['Basic Salary', formatMoney(b.basicSalary)],
      ['Travel Allow.', formatMoney(b.travelAllowance)],
      ['Overtime Pay', formatMoney(b.overtimePay)],
      ['No Leave Bonus', formatMoney(b.noLeaveIncentive)],
    ];
    const deductions = [
      ['Late Deduction', formatMoney(b.lateDeduction)],
      ['Lunch Deduct.', formatMoney(b.lunchOverDeduction)],
      ['Salary Advance', formatMoney(b.salaryAdvance)],
      ['Absent Deduct.', formatMoney(b.absenceDeduction)],
    ];

    earnings.forEach(([label, value], idx) => {
      const rowY = y + idx * 12;
      doc.text(`${label}  ₹${value}`, 40, rowY);
    });
    deductions.forEach(([label, value], idx) => {
      const rowY = y + idx * 12;
      doc.text(`${label}  ₹${value}`, pageWidth / 2 + 20, rowY);
    });

    y += 64;
    doc.setFont(undefined, 'bold');
    doc.text(`GROSS SALARY    ₹${formatMoney(b.grossSalary)}`, 40, y);
    y += 14;
    doc.text(`TOTAL DEDUCT.   ₹${formatMoney(b.totalDeductions + b.salaryAdvance)}`, 40, y);
    y += 18;
    doc.setFontSize(12);
    doc.text(`NET SALARY: ₹${formatMoney(b.netSalary)}`, 40, y);
    y += 18;
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.text(`ESI Amount : ₹${formatMoney(b.esiDeduction)}`, 40, y);

    const footerY = doc.internal.pageSize.getHeight() - 28;
    doc.setFontSize(8);
    doc.text('Generated by PunchPay | punchpay.in', pageWidth / 2, footerY, { align: 'center' });

    const safeName = `${payrollRow.employee_name || 'Employee'}`.replace(/\s+/g, '');
    const d = new Date(payrollRow.year, payrollRow.month - 1, 1);
    const monthStr = d.toLocaleString('default', { month: 'short', year: 'numeric' }).replace(/\s+/g, '');
    const filename = `PunchPay_${safeName}_${monthStr}.pdf`;
    savePdf(doc, filename);
  };

  const handleShareWhatsappSummary = () => {
    const att = breakdown.attendance;
    const b = breakdown.breakdown;
    const payslipText = `
PAYSLIP — ${periodLabel}
${company?.name || ''}

Employee: ${payrollRow.employee_name} (${payrollRow.employee_code})
─────────────────────
ATTENDANCE
Present: ${att?.presentDays ?? '—'} days
Absent: ${att?.absenceDays ?? '—'} days
Late: ${attendanceDetails?.lateCount ?? '—'} times
Overtime: ${att?.overtimeHours ?? '—'} hrs

SALARY
Gross: ₹${formatMoney(b.grossSalary)}
Deductions: ₹${formatMoney(b.totalDeductions + b.salaryAdvance)}
Net Salary: ₹${formatMoney(b.netSalary)}
─────────────────────
Generated by PunchPay
punchpay.in
`;
    const waUrl = `https://wa.me/?text=${encodeURIComponent(payslipText)}`;
    window.open(waUrl, '_blank', 'noopener');
  };

  const handleWhatsappToNumber = () => {
    if (!attendanceDetails?.phone) return;
    const digits = String(attendanceDetails.phone).replace(/[^\d]/g, '');
    if (!digits) return;
    const waUrl = `https://wa.me/${digits}`;
    window.open(waUrl, '_blank', 'noopener');
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-3 print:static print:bg-transparent"
      onClick={onClose}
    >
      <div
        className="w-full max-w-3xl max-h-[95vh] overflow-y-auto rounded-2xl bg-white shadow-2xl border border-slate-200 print:max-h-none print:shadow-none print:border-0"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-6 py-4 backdrop-blur print:hidden">
          <div>
            <h2 className="text-base font-semibold text-slate-900">Payslip</h2>
            <p className="text-xs text-slate-500">
              {payrollRow.employee_name} ({payrollRow.employee_code}) — {periodLabel}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-full p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600"
          >
            ✕
          </button>
        </div>

        <div className="px-6 py-5 space-y-4 print:px-10 print:py-8">
          <header className="border-b border-slate-200 pb-3 text-center">
            <h1 className="text-lg font-semibold tracking-wide text-slate-900">
              {company?.name || 'Company'}
            </h1>
            <p className="mt-1 text-[11px] text-slate-600">
              {[company?.address, company?.phone, company?.email].filter(Boolean).join(' | ')}
            </p>
            <p className="mt-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
              PAYSLIP
            </p>
            <p className="mt-0.5 text-[11px] text-slate-500">Month: {periodLabel}</p>
          </header>

          <section className="grid gap-4 rounded-xl border border-slate-100 bg-slate-50/80 px-4 py-3 text-[11px] text-slate-700 sm:grid-cols-2">
            <div className="space-y-1.5">
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Employee Name</span>
                <span className="font-semibold text-slate-900">{payrollRow.employee_name}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Employee Code</span>
                <span className="font-semibold text-slate-900">{payrollRow.employee_code}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Designation</span>
                <span>{attendanceDetails?.designation || '—'}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Department</span>
                <span>{attendanceDetails?.department || '—'}</span>
              </div>
            </div>
            <div className="space-y-1.5">
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Date of Joining</span>
                <span>{attendanceDetails?.join_date || '—'}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Shift</span>
                <span>{attendanceDetails?.shift_name || '—'}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Working Days</span>
                <span>{breakdown.attendance?.workingDays ?? '—'}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-slate-600">Overtime Hours</span>
                <span>{breakdown.attendance?.overtimeHours ?? '—'}</span>
              </div>
            </div>
          </section>

          <section className="rounded-xl border border-slate-100 bg-white px-4 py-3 text-[11px] text-slate-700">
            <h3 className="mb-2 text-[11px] font-semibold tracking-wide text-slate-600">
              ATTENDANCE SUMMARY
            </h3>
            <div className="grid gap-x-6 gap-y-1.5 sm:grid-cols-2">
              <div className="flex justify-between">
                <span>Working Days</span>
                <span className="font-medium">{breakdown.attendance?.workingDays ?? '—'}</span>
              </div>
              <div className="flex justify-between">
                <span>Days Present</span>
                <span className="font-medium">{breakdown.attendance?.presentDays ?? '—'}</span>
              </div>
              <div className="flex justify-between">
                <span>Days Absent</span>
                <span className="font-medium text-rose-600">
                  {breakdown.attendance?.absenceDays ?? '—'}
                </span>
              </div>
              <div className="flex justify-between">
                <span>Half Days</span>
                <span className="font-medium text-amber-600">
                  {attendanceDetails?.halfDayCount ?? '—'}
                </span>
              </div>
              <div className="flex justify-between">
                <span>Late Arrivals</span>
                <span className="font-medium text-amber-700">
                  {attendanceDetails?.lateCount ?? '—'} times
                </span>
              </div>
              <div className="flex justify-between">
                <span>Overtime Hours</span>
                <span className="font-medium text-emerald-700">
                  {breakdown.attendance?.overtimeHours ?? '—'} hrs
                </span>
              </div>
            </div>
            <div className="mt-3 text-[11px] text-slate-600">
              <p className="font-semibold">Absent Dates:</p>
              <p className="mt-0.5">
                {(attendanceDetails?.absentDates || []).length
                  ? attendanceDetails.absentDates.join(', ')
                  : '—'}
              </p>
              <p className="mt-2 font-semibold">Late Arrival Dates:</p>
              <p className="mt-0.5">
                {(attendanceDetails?.lateDetails || []).length
                  ? attendanceDetails.lateDetails
                      .map((d) =>
                        d.minutes
                          ? `${d.date} - ${d.minutes} mins late`
                          : d.date
                      )
                      .join(', ')
                  : '—'}
              </p>
              <p className="mt-2 font-semibold">Half Day Dates:</p>
              <p className="mt-0.5">
                {(attendanceDetails?.halfDayDates || []).length
                  ? attendanceDetails.halfDayDates.join(', ')
                  : '—'}
              </p>
            </div>
          </section>

          <section className="grid gap-4 rounded-xl border border-slate-100 bg-white px-4 py-3 text-[11px] text-slate-700 sm:grid-cols-2">
            <div>
              <h3 className="mb-2 text-[11px] font-semibold tracking-wide text-slate-600">
                EARNINGS
              </h3>
              <div className="space-y-1.5">
                <div className="flex justify-between">
                  <span>Basic Salary</span>
                  <span className="font-medium">₹{formatMoney(breakdown.breakdown?.basicSalary)}</span>
                </div>
                <div className="flex justify-between">
                  <span>Travel Allow.</span>
                  <span className="font-medium">
                    ₹{formatMoney(breakdown.breakdown?.travelAllowance)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Overtime Pay</span>
                  <span className="font-medium text-emerald-700">
                    ₹{formatMoney(breakdown.breakdown?.overtimePay)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>No Leave Bonus</span>
                  <span className="font-medium text-emerald-700">
                    ₹{formatMoney(breakdown.breakdown?.noLeaveIncentive)}
                  </span>
                </div>
              </div>
            </div>
            <div>
              <h3 className="mb-2 text-[11px] font-semibold tracking-wide text-slate-600">
                DEDUCTIONS
              </h3>
              <div className="space-y-1.5">
                <div className="flex justify-between">
                  <span>Late Deduction</span>
                  <span className="font-medium text-amber-700">
                    ₹{formatMoney(breakdown.breakdown?.lateDeduction)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Lunch Deduct.</span>
                  <span className="font-medium text-amber-700">
                    ₹{formatMoney(breakdown.breakdown?.lunchOverDeduction)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Salary Advance</span>
                  <span className="font-medium text-amber-700">
                    ₹{formatMoney(breakdown.breakdown?.salaryAdvance)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Absent Deduct.</span>
                  <span className="font-medium text-amber-700">
                    ₹{formatMoney(breakdown.breakdown?.absenceDeduction)}
                  </span>
                </div>
              </div>
            </div>
          </section>

          <section className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-3 text-[11px] text-slate-800">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold text-slate-700">Gross Salary</p>
                <p className="text-base font-semibold text-slate-900">
                  ₹{formatMoney(breakdown.breakdown?.grossSalary)}
                </p>
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-700">Total Deductions</p>
                <p className="text-sm font-semibold text-amber-700">
                  ₹{formatMoney(breakdown.breakdown?.totalDeductions + breakdown.breakdown?.salaryAdvance)}
                </p>
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-700">NET SALARY</p>
                <p className="text-lg font-bold text-emerald-700">
                  ₹{formatMoney(breakdown.breakdown?.netSalary)}
                </p>
              </div>
              <div>
                <p className="text-[11px] text-slate-600">ESI Amount</p>
                <p className="text-sm font-medium text-slate-800">
                  ₹{formatMoney(breakdown.breakdown?.esiDeduction)}
                </p>
              </div>
            </div>
          </section>

          <section className="mt-2 flex flex-wrap items-center justify-between gap-3 border-t border-dashed border-slate-200 pt-3 text-[10px] text-slate-500">
            <span>Generated by PunchPay | punchpay.in</span>
          </section>
        </div>

        <div className="sticky bottom-0 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 bg-white/95 px-6 py-3 backdrop-blur print:hidden">
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              onClick={handleDownloadPdf}
              className="inline-flex items-center rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-blue-700"
            >
              Download PDF
            </button>
            <button
              type="button"
              onClick={handleShareWhatsappSummary}
              className="inline-flex items-center rounded-lg border border-emerald-500 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700 hover:bg-emerald-100"
            >
              Share Summary on WhatsApp
            </button>
            {attendanceDetails?.phone && (
              <button
                type="button"
                onClick={handleWhatsappToNumber}
                className="inline-flex items-center rounded-lg border border-emerald-500 bg-white px-3 py-1.5 text-xs font-medium text-emerald-700 hover:bg-emerald-50"
              >
                Open WhatsApp for Employee
              </button>
            )}
          </div>
          <button
            type="button"
            onClick={handlePrint}
            className="inline-flex items-center rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-100"
          >
            Print
          </button>
        </div>
      </div>
    </div>
  );
}

