import { useMemo, useState } from 'react';
import jsPDF from 'jspdf';
import { Link } from 'react-router-dom';
import ToolPageLayout, { formatCurrency, useSeo } from './ToolPageLayout';

const currentDate = new Date();

export default function PayslipGenerator() {
  useSeo(
    'Free Payslip Generator India | Download PDF | PunchPay',
    'Generate professional salary slips instantly. Free payslip maker for Indian businesses. Download as PDF.'
  );

  const [form, setForm] = useState({
    companyName: 'PunchPay Technologies Pvt Ltd',
    companyAddress: 'Bengaluru, Karnataka',
    month: currentDate.toLocaleString('default', { month: 'long' }),
    year: currentDate.getFullYear(),
    employeeName: 'Rahul Sharma',
    employeeCode: 'EMP001',
    designation: 'Operations Executive',
    department: 'Operations',
    basic: 18000,
    hra: '',
    travelAllowance: 2000,
    otherAllowance: 1500,
    pf: '',
    esi: '',
    tds: 500,
    otherDeduction: 0,
    workingDays: 30,
    daysPresent: 28,
    daysAbsent: 2,
  });
  const [generated, setGenerated] = useState(false);

  const payslip = useMemo(() => {
    const basic = Math.max(Number(form.basic) || 0, 0);
    const grossBase = basic + (Number(form.travelAllowance) || 0) + (Number(form.otherAllowance) || 0);
    const hraAuto = basic * 0.4;
    const hra = form.hra === '' ? hraAuto : Math.max(Number(form.hra) || 0, 0);
    const gross = basic + hra + (Number(form.travelAllowance) || 0) + (Number(form.otherAllowance) || 0);
    const pfAuto = basic * 0.12;
    const esiAuto = gross <= 21000 ? gross * 0.0075 : 0;
    const pf = form.pf === '' ? pfAuto : Math.max(Number(form.pf) || 0, 0);
    const esi = form.esi === '' ? esiAuto : Math.max(Number(form.esi) || 0, 0);
    const tds = Math.max(Number(form.tds) || 0, 0);
    const otherDeduction = Math.max(Number(form.otherDeduction) || 0, 0);
    const totalDeductions = pf + esi + tds + otherDeduction;
    const netSalary = gross - totalDeductions;

    return { basic, hra, gross, pf, esi, tds, otherDeduction, totalDeductions, netSalary, grossBase };
  }, [form]);

  const setValue = (key, value) => setForm((prev) => ({ ...prev, [key]: value }));

  const handleGenerate = () => setGenerated(true);

  const handleDownloadPdf = () => {
    const doc = new jsPDF('p', 'pt', 'a4');
    let y = 40;
    const left = 50;
    const right = 545;

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text(String(form.companyName || 'PunchPay'), 297, y, { align: 'center' });
    y += 18;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(String(form.companyAddress || ''), 297, y, { align: 'center' });
    y += 20;
    doc.line(left, y, right, y);
    y += 24;

    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('PAYSLIP', 297, y, { align: 'center' });
    y += 16;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`${form.month} ${form.year}`, 297, y, { align: 'center' });
    y += 16;
    doc.line(left, y, right, y);
    y += 22;

    doc.text(`Employee: ${form.employeeName}`, left, y);
    doc.text(`Code: ${form.employeeCode}`, right, y, { align: 'right' });
    y += 16;
    doc.text(`Designation: ${form.designation}`, left, y);
    y += 18;
    doc.line(left, y, right, y);
    y += 22;

    doc.setFont(undefined, 'bold');
    doc.text('EARNINGS', left, y);
    doc.text('DEDUCTIONS', 320, y);
    y += 16;
    doc.setFont(undefined, 'normal');

    const rows = [
      ['Basic', payslip.basic, 'PF', payslip.pf],
      ['HRA', payslip.hra, 'ESI', payslip.esi],
      ['TA', Number(form.travelAllowance) || 0, 'TDS', payslip.tds],
      ['Other', Number(form.otherAllowance) || 0, 'Other', payslip.otherDeduction],
    ];
    rows.forEach(([eLabel, eValue, dLabel, dValue]) => {
      doc.text(String(eLabel), left, y);
      doc.text(formatCurrency(eValue), 250, y, { align: 'right' });
      doc.text(String(dLabel), 320, y);
      doc.text(formatCurrency(dValue), right, y, { align: 'right' });
      y += 16;
    });

    doc.line(left, y, right, y);
    y += 16;
    doc.setFont(undefined, 'bold');
    doc.text('GROSS', left, y);
    doc.text(formatCurrency(payslip.gross), 250, y, { align: 'right' });
    doc.text('TOTAL', 320, y);
    doc.text(formatCurrency(payslip.totalDeductions), right, y, { align: 'right' });
    y += 18;
    doc.line(left, y, right, y);
    y += 20;
    doc.text(`NET SALARY: ${formatCurrency(payslip.netSalary)}`, left, y);
    y += 20;
    doc.line(left, y, right, y);
    y += 18;
    doc.setFont(undefined, 'normal');
    doc.text('Generated by PunchPay | punchpay.in', 297, y, { align: 'center' });

    doc.save(`Payslip_${form.employeeCode || 'Employee'}_${form.month}_${form.year}.pdf`);
  };

  return (
    <ToolPageLayout toolName="Payslip Generator">
      <h1 className="text-2xl font-bold md:text-3xl">Free Payslip Generator India — Download PDF Payslip Instantly</h1>

      <section className="mt-6 grid gap-4 lg:grid-cols-2">
        <div className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <h2 className="text-lg font-semibold">Input Details</h2>

          <div className="grid gap-3 sm:grid-cols-2">
            <Field label="Company Name" value={form.companyName} onChange={(v) => setValue('companyName', v)} />
            <Field label="Company Address" value={form.companyAddress} onChange={(v) => setValue('companyAddress', v)} />
            <Field label="Month" value={form.month} onChange={(v) => setValue('month', v)} />
            <Field label="Year" type="number" value={form.year} onChange={(v) => setValue('year', v)} />
            <Field label="Employee Name" value={form.employeeName} onChange={(v) => setValue('employeeName', v)} />
            <Field label="Employee Code" value={form.employeeCode} onChange={(v) => setValue('employeeCode', v)} />
            <Field label="Designation" value={form.designation} onChange={(v) => setValue('designation', v)} />
            <Field label="Department" value={form.department} onChange={(v) => setValue('department', v)} />
            <Field label="Basic Salary (₹)" type="number" value={form.basic} onChange={(v) => setValue('basic', v)} />
            <Field label="HRA (₹)" type="number" value={form.hra} onChange={(v) => setValue('hra', v)} placeholder="Auto-calc 40%" />
            <Field
              label="Travel Allowance (₹)"
              type="number"
              value={form.travelAllowance}
              onChange={(v) => setValue('travelAllowance', v)}
            />
            <Field label="Other Allowance (₹)" type="number" value={form.otherAllowance} onChange={(v) => setValue('otherAllowance', v)} />
            <Field label="PF (₹)" type="number" value={form.pf} onChange={(v) => setValue('pf', v)} placeholder="Auto-calc 12%" />
            <Field label="ESI (₹)" type="number" value={form.esi} onChange={(v) => setValue('esi', v)} placeholder="Auto-calc" />
            <Field label="TDS (₹)" type="number" value={form.tds} onChange={(v) => setValue('tds', v)} />
            <Field label="Other Deduction (₹)" type="number" value={form.otherDeduction} onChange={(v) => setValue('otherDeduction', v)} />
            <Field label="Working Days" type="number" value={form.workingDays} onChange={(v) => setValue('workingDays', v)} />
            <Field label="Days Present" type="number" value={form.daysPresent} onChange={(v) => setValue('daysPresent', v)} />
            <Field label="Days Absent" type="number" value={form.daysAbsent} onChange={(v) => setValue('daysAbsent', v)} />
          </div>

          <button
            type="button"
            onClick={handleGenerate}
            className="w-full rounded-lg bg-slate-900 px-4 py-3 text-sm font-bold text-white hover:bg-slate-700"
          >
            Generate Payslip
          </button>
        </div>

        <div className="space-y-4">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 className="mb-3 text-lg font-semibold">Live Preview</h2>
            <div className="rounded-xl border-2 border-slate-900 bg-white p-4 text-sm">
              <div className="border-b border-slate-800 pb-2 text-center">
                <p className="font-bold uppercase">{form.companyName}</p>
                <p className="text-xs">{form.companyAddress}</p>
              </div>
              <div className="border-b border-slate-800 py-2 text-center">
                <p className="font-bold">PAYSLIP</p>
                <p>{form.month} {form.year}</p>
              </div>
              <div className="border-b border-slate-800 py-2">
                <p>Employee: {form.employeeName} | Code: {form.employeeCode}</p>
                <p>Designation: {form.designation}</p>
              </div>
              <div className="border-b border-slate-800 py-2">
                <div className="mb-1 grid grid-cols-2 font-semibold">
                  <span>EARNINGS</span>
                  <span>DEDUCTIONS</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <AmountRow label="Basic" amount={payslip.basic} />
                    <AmountRow label="HRA" amount={payslip.hra} />
                    <AmountRow label="TA" amount={Number(form.travelAllowance) || 0} />
                  </div>
                  <div>
                    <AmountRow label="PF" amount={payslip.pf} />
                    <AmountRow label="ESI" amount={payslip.esi} />
                    <AmountRow label="TDS" amount={payslip.tds} />
                  </div>
                </div>
              </div>
              <div className="border-b border-slate-800 py-2">
                <p>GROSS: {formatCurrency(payslip.gross)} | TOTAL: {formatCurrency(payslip.totalDeductions)}</p>
              </div>
              <div className="border-b border-slate-800 py-2 font-bold">NET SALARY: {formatCurrency(payslip.netSalary)}</div>
              <p className="pt-2 text-center text-xs text-slate-600">Generated by PunchPay | punchpay.in</p>
            </div>

            <button
              type="button"
              onClick={handleDownloadPdf}
              className="mt-4 w-full rounded-lg bg-blue-600 px-4 py-3 text-sm font-bold text-white hover:bg-blue-500"
            >
              Download PDF
            </button>
          </div>

          {generated && (
            <div className="rounded-2xl border border-blue-200 bg-blue-50 p-5">
              <p className="text-sm font-medium text-blue-900">
                You just created 1 payslip manually. Imagine doing this for 20 employees every month.
              </p>
              <p className="mt-2 text-sm text-blue-900">
                PunchPay generates all payslips automatically from attendance data.
              </p>
              <Link
                to="/register"
                onClick={() => console.log('Tool conversion:', 'Payslip Generator')}
                className="mt-4 inline-flex rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white"
              >
                Automate My Payroll {'->'}
              </Link>
            </div>
          )}
        </div>
      </section>
    </ToolPageLayout>
  );
}

function Field({ label, value, onChange, type = 'text', placeholder }) {
  return (
    <label className="block">
      <span className="mb-1 block text-xs font-medium text-slate-600">{label}</span>
      <input
        type={type}
        value={value}
        placeholder={placeholder}
        onChange={(e) => onChange(e.target.value)}
        className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
      />
    </label>
  );
}

function AmountRow({ label, amount }) {
  return (
    <div className="flex items-center justify-between text-xs">
      <span>{label}</span>
      <span>{formatCurrency(amount)}</span>
    </div>
  );
}
